package db

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"
)

type store interface {
	Querier
}

// SQLStore provides an implementation of Store interface.
// It embeds *Queries (generated by sqlc) to directly access
// all generated query methods, and also holds a database connection pool.
type SQLStore struct {
    db *pgxpool.Pool
    *Queries
}

// NewStore creates a new SQLStore instance.
// It initializes sqlc-generated Queries with the provided database handle.
func NewStore(db *pgxpool.Pool) *SQLStore {
    return &SQLStore{
        db:      db,
        Queries: New(db),
    }
}

// execTx executes a function within a database transaction.
// It begins a transaction, passes a transaction-bound Queries object to fn,
// commits if fn returns nil, or rolls back on error.
func (store *SQLStore) execTx(ctx context.Context, fn func(*Queries) error) error {
    tx, err := store.db.Begin(ctx)
    if err != nil {
        return err
    }

    q := New(tx) // use the transaction
    err = fn(q)
    if err != nil {
        if rbErr := tx.Rollback(ctx); rbErr != nil {
            return fmt.Errorf("tx err: %v, rb err: %v", err, rbErr)
        }
        return err
    }

    return tx.Commit(ctx)
}